services:
  - type: web
    name: tic-tac-toe-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: APP_URL
        sync: false
      - key: MONGODB_URI
        sync: false